// チャネル名だけを並べる。preload はこのファイルだけを値として import する（zod を preload に持ち込まないため）
export const channelNames = {
  settingsGet: 'settings:get',
  settingsUpdate: 'settings:update',
  workspaceList: 'workspace:list',
  workspaceCreate: 'workspace:create',
  workspaceSwitch: 'workspace:switch',
  workspaceDelete: 'workspace:delete',
  historySearch: 'history:search',
  historyDelete: 'history:delete',
  bookmarkList: 'bookmark:list',
  bookmarkAdd: 'bookmark:add',
  bookmarkUpdate: 'bookmark:update',
  bookmarkDelete: 'bookmark:delete',
  bookmarkMove: 'bookmark:move',
  bookmarkImportChrome: 'bookmark:importChrome',
  bookmarkImportHtml: 'bookmark:importHtml',
  downloadList: 'download:list',
  downloadPause: 'download:pause',
  downloadResume: 'download:resume',
  downloadCancel: 'download:cancel',
  downloadShowInFolder: 'download:showInFolder',
  permissionList: 'permission:list',
  permissionRevoke: 'permission:revoke',
  tabList: 'tab:list',
  tabCreate: 'tab:create',
  tabClose: 'tab:close',
  tabReopenClosed: 'tab:reopenClosed',
  tabActivate: 'tab:activate',
  tabNavigate: 'tab:navigate',
  tabControl: 'tab:control',
  viewSetBounds: 'view:setBounds',
  startupMode: 'startup:mode',
  // Main → Renderer の知らせ（webContents.send。ADR-007）
  settingsChanged: 'settings:changed',
  tabPageChanged: 'tab:pageChanged',
  tabListChanged: 'tab:listChanged',
  downloadChanged: 'download:changed',
  // メニューのショートカットのうち、画面で行うもの（アドレスバーへのフォーカスなど）
  uiCommand: 'ui:command'
} as const
